config/routes.rb
Rails.application.routes.draw do
  
  root to: "todolists#index"
  resources :todolists do
    resources :todoitems  
  end
  resources :accounts
  resources :users
  resources :sessions, only: [:create, :destroy, :new]
  
  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/todoitem.rb
class Todoitem < ActiveRecord::Base
  belongs_to :todolist
  belongs_to :user
  has_and_belongs_to_many :tags
  
  default_scope { order due_date: :asc}
end

app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController
 before_action :set_todolist
  
  def index
    @todoitems = @todolist.todoitems.paginate(page: params[:page], per_page: 5)
  end
  
  def new
	  @todoitem = @todolist.todoitems.new
  end
  
  def show
	@todoitem = @todolist.todoitems.find(params[:id])
  end
  
  def edit
	  @todoitem = @todolist.todoitems.find(params[:id])
  end

  def create
    @todoitem = @todolist.todoitems.new(todoitem_params)
    @todoitem.done = false
    if @todoitem.save
      redirect_to @todolist, notice: "Item successfully added!"
    else
      redirect_to @todolist, alert: "Unable to add item!"    
    end
  end
  
  def update
    @todoitem = @todolist.todoitems.find(params[:id])
    respond_to do |format|
      if @todoitem.update(todoitem_done_params)
        format.html { redirect_to @todolist, notice: 'Todo item was successfully updated.' }
	format.js 
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todoitem = @todolist.todoitems.find(params[:id])
    @todoitem.destroy
    redirect_to @todolist, notice: "Item deleted!"
  end

  private
    def set_todolist
      @todolist = Todolist.find(params[:todolist_id])
    end
    
     def todoitem_done_params
      params.require(:todoitem).permit(:task_title, :due_date, :description, :done)
    end

    def todoitem_params
      params.require(:todoitem).permit(:task_title, :due_date, :description)
    end
end

app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

app/views/todoitems/_editform.html.erb
<%= form_for([@todolist, @todoitem]) do |f| %>
 
  <div class="field">
    <%= f.label :task_title %><br>
    <%= f.text_field :task_title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date, class: 'date_in' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :done%><br>
    <%= f.check_box :done %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todoitems/_newform.html.erb
<%= form_for([@todolist, @todoitem]) do |f| %>
 
  <div class="field">
    <%= f.label :task_title %><br>
    <%= f.text_field :task_title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date, class: 'date_in' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todoitems/_todoitem.html.erb
<div id="todoitem">


       <%if todoitem.done %>
        <span class="check"><%= "#{todoitem.due_date}"%></span>
	<span class="todoitem_title"><%= link_to "#{todoitem.task_title}", todolist_todoitem_path(@todolist, todoitem) %></span>
		
	<%else%>
	    <span class="nocheck"><%= "#{todoitem.due_date}"%></span>
	    <span class="todoitem_title" id="inline"><%= link_to "#{todoitem.task_title}", todolist_todoitem_path(@todolist, todoitem) %></span>
	    <%= f.fields_for :todoitem do |g| %>
	    <%= g.hidden_field :done, value: true %>
	    <%end%><%= f.submit "Mark as done"%>
	
      
  <div>
    <br/>
  </div>
  </div>

app/views/todoitems/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'editform' %>

<%= link_to 'Back', todolist_path(@todolist)%>

app/views/todoitems/index.html.erb
<p id="notice"><%= notice %></p>
<h1>
    <strong>
  <%if @todolist.todoitems.empty? %>
	   <span class="done">
	   <%= @todolist.list_due_date%></span>
	<%else%>
	     <% isdone = true %>
	     <%@todolist.todoitems.each do |todoitem| %>
	          <%if !todoitem.done %>
		     <% isdone = false%>
		     <% break %>
		  <%end%>
	    <%end%>
	    <% if isdone == false %>
		<span class="notdone">
		<%else%>
		<span class="done">
		<%end%>
	    <%= @todolist.list_due_date%></span>
   <%end%>	
</strong>


  <strong>
  <%= @todolist.list_name %></strong>
  |<%= link_to 'New Todo Item', new_todolist_todoitem_path(@todolist) %>
</h1>


<!--  use the form_for outside and have it output for each thing...then it might work.
Or have form_for outside with a submit button for each inside
Then only render for that specific thingy.-->    
<div id="todoitem">
    <%= render @todoitems%>
    <%= will_paginate @todoitems%>
    </div>




<%= link_to 'Edit Todo List', edit_todolist_path(@todolist) %> |
<%= link_to "Delete Todo List", @todolist, 
        data: { confirm: "List will be deleted?" }, 
        method: :delete %> |
<%= link_to 'Back to List of Todo Lists', todolists_path %>

app/views/todoitems/new.html.erb
<h1>New todoitem</h1>

<%= render 'newform' %>

<%= link_to 'Back', todolist_path(@todolist)%>

app/views/todoitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task Title:</strong>
  <%= @todoitem.task_title%>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todoitem.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todoitem.description %>
</p>

<p>
  <strong>Task Completed?:</strong>
  <%= @todoitem.done%>
</p>

  

<%= link_to 'Edit To do Item', edit_todolist_todoitem_path(@todolist, @todoitem) %> |
<%= link_to "Delete Todo item", [@todolist, @todoitem], 
        data: { confirm: "Task will be deleted?" }, 
        method: :delete %> |
<%= link_to 'Back to Todo List', todolist_path(@todolist) %>

app/views/todoitems/update.js.erb
$(".nocheck").addClass("check").removeClass("nocheck")
$(".inline").hide()
$("#notice").html("<%= notice %>")
travers tomorrow
or application.js click reload