config/routes.rb
Rails.application.routes.draw do
  
  root to: "todolists#index"
  resources :todolists do
    resources :todoitems  
  end
  resources :accounts
  resources :users
  resources :sessions, only: [:create, :destroy, :new]
  
  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
  belongs_to :user
  has_many :todoitems
  
  default_scope { order list_due_date: :asc}
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = current_user.todolists.paginate(page: params[:page], per_page: 5)
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
	  @todoitems = @todolist.todoitems.paginate(page: params[:page], per_page: 5)
	   respond_to do |format|
		format.html # show.html.erb
		format.xml
	  end
  end

  # GET /todolists/new
  def new
    @todolist = current_user.todolists.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = current_user.todolists.new(todolist_params)
    @todoitems = @todolist.todoitems
    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: 'Todolist was successfully created.' }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
	  @todoitems = @todolist.todoitems
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = current_user.todolists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:list_due_date, :list_name)
    end
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/todolists/_form.html.erb
<%= form_for(@todolist) do |f| %>
  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% @todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :list_name %><br>
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_due_date %><br>
    <%= f.text_field :list_due_date, class: "date_in" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Todo lists</h1>


   <div class = "todolist">
   

    <% @todolists.each do |todolist| %>
	<%if todolist.todoitems.empty? %>
	   <span class="done">
	   <%= todolist.list_due_date%></span>
	<%else%>
	     <%todolist.todoitems.each do |todoitem| %>
	          <%if !todoitem.done %>
		     <span class = "notdone">
		     <% break %>
		  <%else%>
		      <span class = "done">
		  <%end%>
	    <%end%>
	    <%= todolist.list_due_date%></span>
	<%end%>
        <%= link_to "#{todolist.list_name}", todolist_todoitems_path(todolist), class: "todolist_link" %><br>

      
    <% end %>
   <%= will_paginate @todolists %>


<br>

<%= link_to 'New Todolist', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New todolist</h1>

<%= render 'form' %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <strong>
  <%if @todolist.todoitems.empty? %>
	   <span class="done">
	   <%= @todolist.list_due_date%></span>
	<%else%>
	     <% isdone = true %>
	     <%@todolist.todoitems.each do |todoitem| %>
	          <%if !todoitem.done %>
		     <% isdone = false%>
		     <% break %>
		  <%end%>
	    <%end%>
	    <% if isdone == false %>
		<span class="notdone">
		<%else%>
		<span class="done">
	<%end%>
	    <%= @todolist.list_due_date%></span>
   <%end%>	
</strong>


  <strong>
  <%= @todolist.list_name %></strong>|<%= link_to 'New Todo Item', new_todolist_todoitem_path(@todolist) %>
</h1>
<%=form_for @todolist do |f|%>
<%=f.fields_for :todoitems do |g| %>
     <%if g.done %>
        <span class="check"><%= "#{g.due_date}"%></span>
	<span class="todoitem_title"><%= link_to "#{g.task_title}", todolist_todoitem_path(@todolist, g) %></span>
		
	<%else%>
	    <span class="nocheck"><%= "#{g.due_date}"%></span>
	    <span class="todoitem_title" id="inline"><%= link_to "#{g.task_title}", todolist_todoitem_path(@todolist, g) %></span>
	    <%= g.hidden_field :done, value: true %>
	    <%end%><%= f.submit "Mark as done"%>
    <%end%>
<%end%>


<%= link_to 'Edit Todo List', edit_todolist_path(@todolist) %> |
<%= link_to "Delete Todo List", @todolist, 
        data: { confirm: "List will be deleted?" }, 
        method: :delete %> |
<%= link_to 'Back to List of Todo Lists', todolists_path %>